# Generated by Django 3.2.19 on 2023-07-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230712_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='namn',
            new_name='name',
        ),
    ]
